'use strict';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const app=$('#app'),toastBox=$('#toast'),modal=$('#modal'),KEY='raphy-v8',CODE='060361';
const NAMES=['Le départ','IRM','Kiné','Bloc fictif','Gynécologue','Cave','Architecte','Peinture','Lavabo','Batterie','Nettoyage voiture','Sortie d’école','Dodo princesse','Mission super-héros','Vitrine mojito','Iced caramel macchiato','Douanes de l’amour','Projection Algérie','Pièce aux insectes','Maison impossible','Numéro masqué','Grand escape game','Dossier Mehdi','Les 48 heures','Ce qu’on ne dit pas assez','Dernière porte'];
const D={unlocked:false,current:0,done:{},choices:{},storyDone:false};
let S=(()=>{try{return {...D,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...D}}})();
let tt,skipArmed=false;
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const toast=(m,t=2400)=>{clearTimeout(tt);toastBox.textContent=m;toastBox.classList.add('show');tt=setTimeout(()=>toastBox.classList.remove('show'),t)};
const vib=p=>{try{navigator.vibrate?.(p)}catch{}};
const screen=(h,c='')=>{app.innerHTML='<main class="screen '+c+'">'+h+'</main>';scrollTo(0,0)};
const top=i=>'<div class="topbar"><div class="ghost-pill"><span class="brand-dot"></span>&nbsp; dossier R</div><div class="progress-pill">'+(i+1)+'/26</div></div>';
const hero=(k,t,d='')=>'<section class="hero"><div class="eyebrow">'+k+'</div><h2>'+t+'</h2>'+(d?'<p>'+d+'</p>':'')+'</section>';
const skip=i=>'<button class="skip-link" id="skip">Passer cette séquence</button>';
function wireSkip(i){let b=$('#skip');if(!b)return;b.onclick=()=>{if(!skipArmed){skipArmed=true;b.textContent='Tu confirmes vraiment ? 😏';toast(['Déjà ? Je ne juge pas. Enfin si, un peu.','Hamoud note officiellement cette fuite.','Mehdi affirme qu’il l’aurait réussi. Source : Mehdi.'][Math.floor(Math.random()*3)]);setTimeout(()=>{skipArmed=false;if(b?.isConnected)b.textContent='Passer cette séquence'},3000)}else complete(i,true)}}
function complete(i,sk=false){S.done[i]=true;S.current=Math.min(i+1,25);save();if(sk)toast('Séquence passée. Le dossier fait semblant de ne rien avoir vu.');setTimeout(()=>route(S.current),180)}
function dots(n,i){return '<div class="stepper">'+Array.from({length:n},(_,x)=>'<i class="'+(x<=i?'on':'')+'"></i>').join('')+'</div>'}
function lock(){
screen('<div class="lock-mark">🔒</div>'+hero('Accès restreint','Une personne seulement.','Si tu n’es pas Raphy, pose ce téléphone avec beaucoup de dignité.')+'<div class="card glow"><input id="pin" class="code-input" inputmode="numeric" maxlength="6" placeholder="••••••"><div class="actions" style="margin-top:12px"><button class="btn" id="go">Entrer</button><button class="btn secondary" id="hint">Tu veux un indice ?</button></div><div id="hz" class="hint-zone"></div></div>','centered');
let tries=0,h=0,dodge=0;const attempt=()=>{tries++;if($('#pin').value===CODE){S.unlocked=true;save();vib([30,30,60]);toast('Bon. C’était bien toi. J’avais un doute extrêmement injustifié.');setTimeout(opening,500)}else{$('#pin').value='';toast(['Non. Mais la confiance était magnifique.','Le code demande un avocat.','Six chiffres ont bien été saisis. C’est déjà quelque chose.','Raphy a choisi la confiance. Le clavier recommande la prudence.'][Math.min(tries-1,3)])}};
$('#go').onclick=attempt;$('#pin').onkeydown=e=>e.key==='Enter'&&attempt();
$('#hint').onclick=()=>{h++;if(h===1){$('#hz').innerHTML='<div class="card soft"><b>Haha…</b><br>Tu peux pas te passer de moi deux minutes ? Tu veux VRAIMENT un indice ?<div class="actions two" style="margin-top:12px"><button class="btn small" id="yes">Oui 🙄</button><button class="btn small secondary runaway" id="no">Non</button></div></div>';let no=$('#no'),z=$('#hz');const run=()=>{dodge++;no.style.left=Math.random()*Math.max(20,z.clientWidth-no.offsetWidth-20)+'px';no.style.top=(35+Math.random()*25)+'px';if(dodge>2){no.textContent='Très courageuse.';setTimeout(()=>no.remove(),500)}};no.onpointerenter=run;no.onclick=run;$('#yes').onclick=()=>$('#hz').innerHTML='<div class="card soft"><b>Indice 1 :</b> une date commune. Six chiffres. Non, 123456 n’est pas romantique.</div>'}else if(h===2)$('#hz').innerHTML='<div class="card soft"><b>Indice 2 :</b> ça commence par <b>06</b>. Là je t’aide beaucoup trop.</div>';else $('#hz').innerHTML='<div class="card soft"><b>Bon :</b> 06 • 03 • 61. Si tu rates encore, le clavier demande une pause.</div>'};
}
function opening(){screen('<div class="memory-scene" style="min-height:390px;background:linear-gradient(160deg,#362538,#0b0a10)"><div style="position:absolute;inset:0;display:grid;place-items:center"><div style="width:230px;height:150px;border-radius:12px;background:#efe4da;transform:rotate(-4deg);display:grid;place-items:center;color:#3f3040;font:22px Georgia">Pour Raphy</div></div><div class="memory-copy"><h3>J’avais prévu quelque chose de simple.</h3><p>Puis Hamoud a touché un truc.</p></div></div><div class="card"><p class="storyline">À l’intérieur : une clé, une photo retournée et une phrase : <i>« Suis les traces. Certaines sont à toi. D’autres… te connaissent déjà. »</i></p></div><button class="btn" id="o">Ouvrir</button>');$('#o').onclick=()=>story(0)}
const STORY=[
['Le magasin de lunettes','Mehdi entre dans un magasin de lunettes. Puis il te voit : cheveux framboise, sourire beaucoup trop efficace, répartie déjà prête. Il était venu pour des lunettes. Le scénario avait manifestement d’autres projets.',['Le clasher immédiatement.','Faire comme si tu n’avais rien remarqué.','Le regarder deux secondes de trop.']],
['Deux cigarettes','Quelques jours plus tard, vers 18 h, tu passes dans son magasin. Officiellement : deux cigarettes. Officieusement : le prétexte le moins discret de l’année.',['« J’ai vraiment besoin de deux cigarettes. »','« Et si je voulais juste te parler ? »','Repartir avec une dignité très théorique.']],
['Deux Cristaline','Vers 19 h, tu reviens avec deux bouteilles de Cristaline pour le remercier. Deux bouteilles pour deux cigarettes : probablement le meilleur rendement romantique de 2026.',['Investissement prudent.','C’était juste pour remercier. Bien sûr.','Refuser tout commentaire sur la Cristaline.']],
['L’appel et Snapchat','Mehdi appelle ton magasin parce qu’il veut te reparler. Après le travail, vous discutez vraiment. Puis la grande négociation diplomatique : Snapchat.',['Dire oui tout de suite.','Le faire patienter deux secondes.','Prétendre que c’est une décision administrative.']],
['Salon-de-Provence','Restaurant, voyages, États-Unis, anecdotes. Puis la balade et cette balançoire en pneu, vous deux en quinconce à regarder le ciel comme si la soirée avait décidé de ralentir.',['Rester sans parler.','Raconter encore une anecdote.','Dire « c’est incroyable ».']],
['Et évidemment… la police','La police vous demande finalement de partir pendant une intervention liée à quatre jeunes et un faux pistolet. Vous continuez à parler dans la voiture. Première soirée normale : demande refusée.',['En rire.','Faire comme si tout était prévu.','Demander UNE soirée normale.']],
['11/05 — la plage','Plage, nappe, makis poulet, samoussas. Puis le premier baiser, initié par Mehdi — détail qu’il voudrait évidemment faire authentifier.',['Laisser le moment exister.','Le taquiner avant.','Le faire patienter encore une seconde.']]
];
function story(i){if(i>=STORY.length){S.storyDone=true;save();return reveal()}let s=STORY[i];screen(dots(STORY.length,i)+'<div class="memory-scene" style="min-height:380px;background:linear-gradient(150deg,#6b5064,#25202a 52%,#0d0c11)"><div class="memory-copy"><div class="eyebrow">Avant les portes</div><h3>'+s[0]+'</h3><p>'+s[1]+'</p></div></div><div class="card"><div class="eyebrow">Raphy fait quoi ?</div><div class="choices" style="margin-top:12px">'+s[2].map((x,j)=>'<button class="choice" data-a="'+j+'">'+x+'</button>').join('')+'</div></div>');$$('[data-a]').forEach(b=>b.onclick=()=>{S.choices['story'+i]=+b.dataset.a;save();toast(['Le dossier note cette version avec un sourcil levé.','Choix enregistré. Hamoud refuse de commenter.','Mehdi prépare déjà un droit de réponse.'][+b.dataset.a]);setTimeout(()=>story(i+1),600)})}
function reveal(){screen('<div class="eyebrow">Dossier ouvert</div><section class="hero"><h1 class="big-title">Sur les traces<br><span class="scriptish">de Raphy</span></h1><p>Pas un album souvenir. Une maison qui garde les détails, même ceux que tu n’avais pas remarqués.</p></section><div class="card"><p class="storyline">La première porte s’ouvre. Derrière : une journée où ton dos décide de déposer officiellement sa démission.</p></div><button class="btn" id="r">Entrer</button>','centered');$('#r').onclick=()=>route(0)}
const QG=[
['Le logiciel indique : « motif de consultation — installation d’une vasque double ». Je confirme que ce n’est pas vous qui fuyez sous l’évier ?',['Non docteur. Enfin j’espère.','Ça dépend, vous avez du Téflon ?','Mehdi a rempli le formulaire, ça explique beaucoup.']],
['Sur une échelle de 1 à 10, votre patience avec les formulaires administratifs est-elle encore couverte par la Sécurité sociale ?',['6, mais ça baisse.','Je demande une ALD pour paperasse chronique.','Elle est décédée à la page 2.']],
['Le dossier mentionne « eau chaude inversée avec eau froide ». Nous parlons TOUJOURS du lavabo ?',['Oui. On garde notre dignité.','Je souhaite appeler mon plombier et mon avocat.','Posez la question à Mehdi, il est très sûr de lui.']],
['Avez-vous été exposée à un homme convaincu qu’une pièce restante signifie que le montage est plus efficace ?',['Malheureusement oui.','Exposition quotidienne, sans protection.','Il appelle ça optimisation.']],
['Le système me demande votre groupe sanguin puis la taille du siphon. J’ignore la deuxième question pour notre dignité commune.',['Excellente décision.','Dommage, j’avais révisé.','Le siphon refuse de témoigner.']],
['Votre contact d’urgence est Mehdi. Maintenez-vous cette décision après le trajet jusqu’à l’hôpital ?',['Oui, malgré tout.','Je voudrais consulter les autres candidats.','Seulement si Hamoud est indisponible.']],
['Quand vous dites « ça va », est-ce médical ou une tradition consistant à faire la forte ?',['Un peu des deux.','Je refuse sans mon doudou cochon.','Secret défense.']]
];
const QGIRL=[
['« J’ai soif. Mais pas l’eau de tout à l’heure. L’autre eau. »',['Mini verre.','Expliquer qu’il n’y a qu’une eau.','Appeler Mehdi.']],
['« J’ai envie de faire pipi. Mais je crois seulement à 62%. »',['On tente.','On attend 38%.','Auditer le calcul.']],
['« Mon pied gauche a chaud. Le droit est normal. »',['Sortir le pied gauche.','Échanger les pieds.','Réunion des deux pieds.']],
['« Mon doudou a peur du noir. Moi non. Lui. »',['Veilleuse.','Dire au doudou de grandir.','Hamoud garde du corps.']],
['« J’ai entendu un bruit. Il faisait exactement… bruit. »',['Vérifier vite.','Demander une imitation.','Dire « c’est la maison ».']],
['« Les poissons, ils ont soif ? »',['Excellente question, demain.','Cours sur l’osmose.','Demander à Mehdi.']],
['« Si je dors très fort, demain arrive plus vite ? »',['Oui, teste tout de suite.','Non.','Seulement pendant la sieste espagnole.']]
];
const QBOY=[
['Si Superman met son pyjama par-dessus son costume, il est doublement habillé ou officiellement au lit ?',['Au lit.','Doublement habillé.','Les deux.']],
['Si je sauve le monde avant le dîner, je dois manger les légumes ?',['Oui.','Non.','Seulement les carottes héroïques.']],
['Pourquoi les méchants ont une base secrète mais maman sait toujours où elle est ?',['Maman sait tout.','Google Maps.','Secret défense.']],
['Un super-héros peut avoir un doudou s’il est classé secret défense ?',['Évidemment.','Non.','Seulement avec une cape.']],
['Si Hamoud vole mon masque, il devient mon identité secrète ?',['Oui, malheureusement.','Non.','Seulement la nuit.']],
['Si je cours très vite autour de la maison, demain arrive plus tôt ?',['Non.','Oui.','Demande à la Terre.']],
['Qui gagne entre un dinosaure invisible et un robot qui sait qu’il est invisible ?',['Le dinosaure.','Le robot.','Personne ne peut répondre.']]
];
function quiz(i,title,sub,qs,emo){let q=0;screen(top(i)+hero('Trace '+String(i+1).padStart(2,'0'),title,sub)+'<div class="card" id="qc"></div>'+skip(i));wireSkip(i);const c=$('#qc');const draw=()=>{if(q>=qs.length){c.innerHTML='<div style="font-size:70px;text-align:center">'+emo+'</div><h3>Mission terminée.</h3><button class="btn" id="qd">Continuer</button>';$('#qd').onclick=()=>complete(i);return}let z=qs[q];c.innerHTML=dots(qs.length,q)+'<div class="dialogue" style="margin-top:16px"><div class="avatar">'+emo+'</div><div class="bubble">'+z[0]+'</div></div><div class="choices" style="margin-top:14px">'+z[1].map((x,j)=>'<button class="choice" data-q="'+j+'">'+x+'</button>').join('')+'</div>';$$('[data-q]',c).forEach(b=>b.onclick=()=>{toast(['Réponse enregistrée. Le dossier hoche la tête.','Choix audacieux. Aucun remboursement prévu.','Hamoud estime que c’est défendable.'][+b.dataset.q]);q++;setTimeout(draw,430)})};draw()}
function simpleOrder(i,title,desc,order,icons,finish){let p=0;screen(top(i)+hero('Trace '+String(i+1).padStart(2,'0'),title,desc)+'<div class="game-stage" style="display:grid;place-items:center"><div id="build" style="font-size:86px">🧰</div></div><div class="item-grid">'+icons.map((x,j)=>'<button class="item" data-o="'+j+'">'+x+'</button>').join('')+'</div><p class="caption" id="ol">Étape 1/'+order.length+'</p>'+skip(i));wireSkip(i);$$('[data-o]').forEach(b=>b.onclick=()=>{let j=+b.dataset.o;if(j===order[p]){b.disabled=true;b.classList.add('selected');p++;$('#ol').textContent='Étape '+Math.min(p+1,order.length)+'/'+order.length;toast('Ça rentre. Mehdi dit évidemment qu’il savait.');if(p===order.length){toast(finish);setTimeout(()=>complete(i),700)}}else toast('Non. Cette pièce vient de demander à retourner dans sa boîte.')})}
function departure(){let v=50,x=0,press=false;screen(top(0)+hero('Trace 01','Le départ','Aide Raphy à avancer sans la porter comme un colis fragile.')+'<div class="game-stage" id="walk"><div style="position:absolute;left:10%;right:10%;bottom:55px;height:8px;background:#403747;border-radius:20px"><div id="w" style="position:absolute;left:0;top:-38px;font-size:38px">🚶‍♀️</div></div><div style="position:absolute;right:20px;top:20px;font-size:48px">🐈</div></div><div class="card"><div class="meter"><i id="m" style="width:50%"></i></div><p id="l" class="caption">Maintiens l’écran : plus de soutien. Relâche : moins.</p></div>'+skip(0));wireSkip(0);let st=$('#walk'),m=$('#m'),w=$('#w');st.onpointerdown=e=>{e.preventDefault();press=true};st.onpointerup=()=>press=false;st.onpointercancel=()=>press=false;let last=performance.now();const loop=t=>{if(!st.isConnected)return;let dt=Math.min(40,t-last)/16;last=t;v+=press?1.2*dt:-.7*dt;v=Math.max(5,Math.min(95,v));m.style.width=v+'%';if(v>40&&v<68){x+=.14*dt;w.style.left=Math.min(88,x)+'%'}if(x>=88){toast('Appartement quitté. Hamoud dépose une réclamation officielle.');setTimeout(()=>complete(0),600);return}requestAnimationFrame(loop)};requestAnimationFrame(loop)}
function mri(){let p=0,still=100;screen(top(1)+hero('Trace 02','IRM : ne bouge pas','Le nez qui coule a choisi son moment.')+'<div class="game-stage" style="display:grid;place-items:center;background:linear-gradient(#dfe6eb,#606a73 55%,#15181b)"><div style="font-size:82px">😐</div><button class="btn small secondary" id="itch" style="position:absolute;left:14px;bottom:14px">Ça gratte</button><button class="btn small secondary" id="nose" style="position:absolute;right:14px;bottom:14px">Nez 🤧</button></div><div class="card"><div class="meter cold"><i id="scan"></i></div><p id="ml" class="caption">Ne touche à rien. Oui, les boutons sont là exprès.</p></div>'+skip(1));wireSkip(1);$('#itch').onclick=()=>{still-=18;toast('La machine vient de créer un Picasso médical.')};$('#nose').onclick=()=>{still-=12;toast('Dignité : en cours de négociation.')};let it=setInterval(()=>{if(!$('#scan'))return clearInterval(it);p+=2;$('#scan').style.width=p+'%';if(p===44)$('#ml').textContent='Le scanner reconstruit un tatouage : « New… Pork ? »';if(p>=100){clearInterval(it);toast(still>80?'Immobile. Impressionnant.':'Scan terminé. Les tatouages demandent une seconde opinion graphique.');setTimeout(()=>complete(1),600)}},150)}
function timing(i,title){let q=0,ok=false,score=0;let names=['Flamant administratif','Chaise invisible de la CAF','Pont très optimiste','Chat qui regrette ses choix','Respiration « je vais bien »'];screen(top(i)+hero('Trace 03',title,'Quand le bouton devient doré, tape.')+'<div class="game-stage" style="display:grid;place-items:center"><div id="pose" style="font-size:90px">🦩</div></div><div class="card"><h3 id="tn">'+names[0]+'</h3><button class="btn" id="tap">Synchroniser</button><p class="caption">Score : <b id="ts">0</b></p></div>'+skip(i));wireSkip(i);const next=()=>{if(q>=5){toast('Kiné validée. Hamoud demande une médaille.');return setTimeout(()=>complete(i),600)}ok=false;$('#tn').textContent=names[q];$('#tap').style.filter='';setTimeout(()=>{ok=true;$('#tap').style.filter='brightness(1.4)';setTimeout(()=>{ok=false;$('#tap').style.filter=''},450)},650+Math.random()*700)};$('#tap').onclick=()=>{if(ok){score++;toast('Timing propre. Le kiné est presque contrarié.')}else toast('Techniquement, c’était un mouvement.');$('#ts').textContent=score;q++;next()};next()}
function gyno(){quiz(4,'Consultation gynéco','Non graphique. Le logiciel, lui, est gravement atteint.',QG,'👩‍⚕️')}
function canvasGame(i,title,clean=false){screen(top(i)+hero('Trace '+String(i+1).padStart(2,'0'),title,clean?'Frotte jusqu’à 100%. À 99%, évidemment, une micro-tache.':'Peins au doigt. Hamoud a promis de ne pas marcher dedans.')+'<div class="canvas-wrap"><canvas id="cv" class="paint-canvas" width="640" height="500"></canvas></div><div class="meter"><i id="bar"></i></div>'+skip(i));wireSkip(i);let c=$('#cv'),x=c.getContext('2d'),down=false,moves=0,done=false;x.fillStyle=clean?'#a9c0cb':'#d6cec3';x.fillRect(0,0,640,500);for(let k=0;k<100;k++){x.fillStyle=clean?'#6e5b4d':'#b4a59b';x.beginPath();x.arc(Math.random()*640,Math.random()*500,6+Math.random()*18,0,7);x.fill()}if(clean)x.globalCompositeOperation='destination-out';const draw=e=>{if(done)return;let r=c.getBoundingClientRect(),px=(e.clientX-r.left)*640/r.width,py=(e.clientY-r.top)*500/r.height;x.beginPath();x.arc(px,py,30,0,7);if(!clean)x.fillStyle='#92706f';x.fill();moves++;let pc=Math.min(100,moves/2.2);$('#bar').style.width=pc+'%';if(pc>=100){done=true;if(!clean){x.font='45px serif';x.fillText('🐾',360,250);toast('Hamoud a ajouté sa signature. Art contemporain.')}else toast('100%. Silence. Respect.');setTimeout(()=>complete(i),800)}};c.onpointerdown=e=>{down=true;draw(e)};c.onpointermove=e=>down&&draw(e);c.onpointerup=()=>down=false;c.onpointercancel=()=>down=false}
function school(){let f=0;screen(top(11)+hero('Trace 12','Sortie d’école','Six affaires à récupérer. Deux conversations fictives à éviter.')+'<div class="game-stage" id="sch" style="background:linear-gradient(#c6d9e8,#91a782)">'+['🎒','🧥','🥤','🧸','🎨','🥿'].map((x,i)=>'<button class="item" data-s style="position:absolute;left:'+(12+(i%3)*29)+'%;top:'+(60+Math.floor(i/3)*120)+'px;width:78px;background:#eee;color:#222">'+x+'</button>').join('')+'<button class="item" id="mom" style="position:absolute;right:12px;bottom:12px;width:110px;background:#f1d7dc;color:#222">👩 « juste 2 min… »</button></div>'+skip(11));wireSkip(11);$$('[data-s]').forEach(b=>b.onclick=()=>{b.disabled=true;b.style.opacity=.2;f++;if(f===6){toast('Six affaires. Zéro réunion de parents improvisée.');setTimeout(()=>complete(11),650)}});$('#mom').onclick=()=>toast('Piège. Tu viens de perdre quatre minutes fictives de ta vie.')}
function mojito(){simpleOrder(14,'Vitrine mojito','Petit niveau esthétique. Une seule vraie blague ici.',[0,1,2,3,4],['🧊 Glace','🍋‍🟩 Citron','🌿 Menthe','🥤 Bulles','🍯 Sucre'],'Cette fois, il y a de la menthe. On progresse.')}
function coffee(){simpleOrder(15,'Iced caramel macchiato','Sa boisson préférée. L’ordre compte.',[0,1,2,3,4],['🍦 Vanille','🥛 Lait','🧊 Glace','☕ Espresso','🍯 Caramel'],'Parfait. Un client fictif voudrait la même chose sans café, sans lait et très café.')}
function customs(){let n=0;screen(top(16)+hero('Trace 17','Douanes de l’amour','Italie, Espagne, Algérie : les pays ne sont pas la blague. Mehdi, souvent, oui.')+'<div class="item-grid">'+['Passeport ❤️','Pâtes non cassées 🇮🇹','Paella symbolique 🇪🇸','Brochure Mehdi 🇩🇿','Hamoud 🐈','Doudou cochon 🐷'].map(x=>'<button class="item big" data-p>'+x+'</button>').join('')+'</div><button class="btn" id="cc">Contrôle</button>'+skip(16));wireSkip(16);$$('[data-p]').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');n+=$(b).classList.contains('selected')?1:-1});$('#cc').onclick=()=>{if(n<4)return toast('Il manque des choses. Le douanier fixe Hamoud avec inquiétude.');toast('Voyage al dente : pas trop long, pas trop cuit. Le douanier regrette sa blague.');setTimeout(()=>complete(16),700)}}
function algeria(){screen(top(17)+hero('Trace 18','Mehdi Immobilier™','Offre totalement objective écrite par le principal bénéficiaire.')+'<div class="memory-scene" style="min-height:400px;background:linear-gradient(#e9a36e,#b96770 42%,#32465c)"><div class="memory-copy"><h3>Deux pièces · cinq enfants · liberté conceptuelle</h3><p>« Terrasse exceptionnelle. Raphy ne sort pas parce qu’elle est tellement bien. Moi, très détendu. »</p></div></div><div class="choices"><button class="choice" data-al="0">Refuser et demander l’adresse de l’agence.</button><button class="choice" data-al="1">Accepter si Mehdi gère les cinq enfants pendant 18 ans.</button><button class="choice" data-al="2">Demander une sixième personnalité pour tenir le planning.</button></div>'+skip(17));wireSkip(17);$$('[data-al]').forEach(b=>b.onclick=()=>{S.choices.algeria=+b.dataset.al;save();toast(['Mehdi retire discrètement la brochure.','L’offre vient de perdre toute rentabilité.','Négociation extrêmement dangereuse.'][+b.dataset.al]);setTimeout(()=>complete(17),700)})}
function horror(){screen(top(18)+hero('Trace 19','La pièce qui bourdonne','Lampe torche. Et quelque chose qui frôle l’écran.')+'<div class="game-stage horror" id="hs" style="min-height:520px;background:#030304"><div id="moths"></div><div class="flashlight" id="fl"></div><button class="btn small secondary" id="lamp" style="position:absolute;right:12px;top:12px;z-index:3">Autre lampe</button><div style="position:absolute;left:18px;bottom:18px;font-size:48px">🐈</div></div>'+skip(18),'horror');wireSkip(18);for(let i=0;i<10;i++){let m=document.createElement('div');m.className='moth';m.style.setProperty('--dur',(3+Math.random()*4)+'s');m.style.left=Math.random()*90+'%';m.style.top=Math.random()*70+'%';$('#moths').append(m)}$('#hs').onpointermove=e=>{let r=$('#hs').getBoundingClientRect();$('#fl').style.setProperty('--x',(e.clientX-r.left)/r.width*100+'%');$('#fl').style.setProperty('--y',(e.clientY-r.top)/r.height*100+'%')};$('#lamp').onclick=()=>{$('#moths').style.transform='translate(25%,-15%)';toast('Bonne idée. Presque toutes les ailes changent de cible.')};setTimeout(()=>{if($('#hs')){vib([20,30,20]);toast('Bruit derrière toi. Hamoud est pourtant juste devant.')}},4500);setTimeout(()=>$('#hs')&&complete(18),10500)}
function house(){let f=0;screen(top(19)+hero('Trace 20','La maison impossible','Tu connais cette pièce. C’est précisément le problème.')+'<div class="game-stage" style="min-height:470px;background:linear-gradient(#493b3a,#171418)"><button class="anomaly" data-an style="left:10%;top:12%;width:90px;height:110px;background:#362c31;color:white">🖼️🐈</button><button class="anomaly" data-an style="right:12%;top:16%;width:80px;height:90px;background:#6d5c51;transform:rotate(180deg)">🖼️</button><button class="anomaly" data-an style="left:34%;bottom:14%;font-size:70px">🪑</button><button class="anomaly" data-an style="right:7%;bottom:8%;width:95px;height:220px;background:#151217;color:white">🚪</button></div>'+skip(19));wireSkip(19);$$('[data-an]').forEach(b=>b.onclick=()=>{if(b.classList.contains('found'))return;b.classList.add('found');f++;toast(f===1?'Le portrait officiel de Hamoud est beaucoup trop sérieux.':'Anomalie trouvée. La pièce prétend que tout va bien.');if(f===4)setTimeout(()=>complete(19),650)})}
function unknown(){let st=0;screen(top(20)+hero('Trace 21','Numéro masqué','Il connaît des réponses données plus tôt.')+'<div class="phone"><div class="phone-top"><span>19:47</span><span>Masqué</span></div><div id="msgs"><div class="msg in">Tu avances vite.</div><div class="msg in">Premier vrai rendez-vous surprise : jour + mois ?</div></div><div id="pa" style="margin-top:12px"><div class="input-row"><input id="d" class="code-input" maxlength="4" inputmode="numeric" placeholder="JJMM"><button class="btn" id="send">OK</button></div></div></div>'+skip(20));wireSkip(20);$('#send').onclick=()=>{if($('#d').value!=='1105')return toast('Non. Le sushi refuse de confirmer cette chronologie.');$('#msgs').innerHTML+='<div class="msg out">1105</div><div class="msg in">Bien. La maison ne vole rien. Elle reconstruit ce que tu changes partout où tu passes.</div>';$('#pa').innerHTML='<button class="btn" id="hang">Raccrocher</button>';$('#hang').onclick=()=>complete(20)}}
function escapeGame(){let p=0;const z=[['Sur l’IRM, quel symbole revient ?',['○','△','♥','□'],2],['Le lavabo mentait sur…',['La taille','Chaud/froid','La hauteur','Le prix'],1],['Premier vrai rendez-vous surprise ?',['2504','0205','1105','1905'],2],['Anomalie la plus absurde de la maison ?',['Chaise','Porte','Portrait de Hamoud','Lumière'],2],['Ce que tu touches laisse une…',['trace','preuve','facture','tache'],0]];screen(top(21)+hero('Trace 22','Le grand escape game','Les détails d’avant reviennent enfin.')+'<div class="card" id="ec"></div>'+skip(21));wireSkip(21);const draw=()=>{if(p>=z.length){$('#ec').innerHTML='<div class="eyebrow">Dernier verrou</div><h2>♥ + ↔ + 1105 + 🐈 + TRACE</h2><p class="storyline">Ce n’est pas un code. C’est une phrase déguisée.</p><button class="btn" id="ed">Ouvrir</button>';$('#ed').onclick=()=>complete(21);return}let q=z[p];$('#ec').innerHTML=dots(z.length,p)+'<h3>'+q[0]+'</h3><div class="choices">'+q[1].map((x,j)=>'<button class="choice" data-e="'+j+'">'+x+'</button>').join('')+'</div><div id="eh"></div>';$$('[data-e]').forEach(b=>b.onclick=()=>{if(+b.dataset.e===q[2]){toast('Oui. Et maintenant tu réalises que ce détail comptait.');p++;setTimeout(draw,450)}else toast('Non. Le verrou fait ce petit silence gênant.')});setTimeout(()=>{if($('#eh'))$('#eh').innerHTML='<button class="btn secondary small" id="hintE">Tu veux un indice ?</button>';if($('#hintE'))$('#hintE').onclick=()=>{$('#hintE').textContent='Vraiment ? 😏';setTimeout(()=>$('#hintE')&&($('#hintE').outerHTML='<div class="card soft">Indice : repense aux scènes précédentes, pas à un code sorti de nulle part.</div>'),550)}},20000)};draw()}
function trial(){let p=0,score=0;const c=[['Le mérite de la cave','Raphy a tout rangé. Mehdi : « on a bien géré ».','Je supervisais moralement.'],['Le trajet hôpital','Plusieurs dos-d’âne ont été traités comme facultatifs.','La route était agressive.'],['Le lavabo','Chaud et froid inversés avec une confiance remarquable.','Le manuel manquait d’ambition.'],['Le plan Algérie premium','Deux pièces, cinq enfants, Mehdi très détendu.','La brochure était en test.'],['Les cinq minutes','Plusieurs cinq minutes ont duré 12 à 47 minutes.','Le temps est relatif.'],['Hamoud chef de projet','Le chat a eu accès aux outils et aux décisions.','Il avait l’air qualifié.']];screen(top(22)+hero('Trace 23','Le dossier Mehdi','Six dossiers. Une défense qui aurait dû rester silencieuse.')+'<div class="card" id="tc"></div>'+skip(22));wireSkip(22);const draw=()=>{if(p>=c.length){$('#tc').innerHTML='<h2>Verdict : '+(score<4?'acquitté de façon suspecte':score<8?'coupable mais encore fréquentable':'très coupable, qu’il arrête de parler')+'.</h2><p>Hamoud fait appel. Personne ne lui a demandé.</p><button class="btn" id="td">Classer</button>';$('#td').onclick=()=>complete(22);return}let x=c[p];$('#tc').innerHTML=dots(c.length,p)+'<h2>'+x[0]+'</h2><p>'+x[1]+'</p><div class="card soft"><b>Défense de Mehdi :</b><br>'+x[2]+'</div><div class="choices" style="margin-top:14px"><button class="choice" data-v="0">Acquitté 😇</button><button class="choice" data-v="1">Coupable 😌</button><button class="choice" data-v="2">Très coupable, qu’il arrête de parler 🔨</button></div>';$$('[data-v]').forEach(b=>b.onclick=()=>{score+=+b.dataset.v;toast(+b.dataset.v===0?'Mehdi sourit beaucoup trop vite.':+b.dataset.v===1?'Il murmure « sorti de son contexte ».':'Le marteau a parlé. Mehdi aussi, mais personne n’écoute.');p++;setTimeout(draw,430)})};draw()}
function calm(){screen(top(23)+hero('Trace 24','Les 48 heures','Pas d’énigme. Pas de score.')+'<div class="memory-scene" style="min-height:430px;background:linear-gradient(145deg,#473b44,#1d1920 56%,#0d0c11)"><div class="memory-copy"><h3>Hôpital, repos, maison.</h3><p>Et <i>Qu’est-ce qu’on a fait au Bon Dieu ?</i> Toi morte de rire. Un souvenir banal, donc précieux.</p></div></div><button class="btn" id="cd">Continuer</button>');$('#cd').onclick=()=>complete(23)}
function unsaid(){let p=0;const a=[['Ta force','Je vois à quel point tu continues, même quand ce serait plus simple de dire que c’est trop.'],['Ton courage','Pas le spectaculaire. Celui du quotidien.'],['Ta place','Tu es importante dans ma vie. Comme une réalité, pas comme une phrase de fin.'],['Toi','Et oui : je te trouve magnifique. Je ne te le dis probablement pas assez.'],['Nous','Au milieu de tout le reste… je t’aime.']];screen(top(24)+hero('Trace 25','La pièce où on ne dit pas assez les choses','Ici, pas de score.')+'<div class="card" id="uc"></div>');const draw=()=>{if(p>=a.length){$('#uc').innerHTML='<div class="heart"></div><h2 style="text-align:center">Il reste une porte.</h2><button class="btn" id="ud">L’ouvrir</button>';$('#ud').onclick=()=>complete(24);return}$('#uc').innerHTML='<div class="eyebrow">'+a[p][0]+'</div><p class="storyline">'+a[p][1]+'</p><button class="btn secondary" id="un">Continuer</button>';$('#un').onclick=()=>{p++;draw()}};draw()}
function final(){S.done[25]=true;save();screen(hero('Dernière porte','Le cœur n’était pas à trouver.','Il était en train de se construire depuis la première porte.')+'<div class="heart"></div><div class="card glow"><p class="storyline">La maison n’avait rien volé. Elle a suivi ce que tu laisses derrière toi : dans les lieux, les journées, les gens, les souvenirs. Des traces.</p><p class="storyline">La suite n’est pas écrite ici. Tant mieux.</p><p class="storyline" style="font-size:30px;text-align:center"><b>Je t’aime ❤️</b></p></div><div class="actions"><button class="btn" id="cr">Générique</button><button class="btn secondary" id="rp">Rejouer</button></div>','centered');$('#cr').onclick=credits;$('#rp').onclick=replay}
function credits(){screen(hero('Générique','Une production parfaitement raisonnable')+'<div class="card credits"><p><b>Raphy</b> — héroïne, spécialiste mondiale du « ça va ».</p><p><b>Mehdi</b> — scénario, confiance disproportionnée, récupération de mérite.</p><p><b>Hamoud</b> — sabotage, direction artistique, expertise non demandée.</p><p><b>La Cristaline</b> — meilleur retour sur investissement romantique de 2026.</p><p><b>Prochain chapitre</b> — vide pour l’instant.</p></div><button class="btn" id="rp">Rejouer</button><button class="btn secondary" id="dev">Zone Mehdi</button>');$('#rp').onclick=replay;$('#dev').onclick=dev}
function replay(){screen(hero('Après le générique','Rejouer une trace')+'<div class="item-grid">'+NAMES.map((x,i)=>'<button class="item big" data-r="'+i+'" '+(S.done[i]?'':'disabled')+'><b>'+String(i+1).padStart(2,'0')+'</b><br>'+x+'</button>').join('')+'</div><div class="card soft"><div class="eyebrow">À venir</div><h3>Chapitre +1</h3><p class="caption">Vide pour l’instant. Volontairement.</p></div>');$$('[data-r]').forEach(b=>b.onclick=()=>route(+b.dataset.r))}
function dev(){modal.hidden=false;modal.innerHTML='<div class="modal-card"><h2>Zone Mehdi</h2><input id="dc" class="code-input" maxlength="6" inputmode="numeric"><div class="actions" style="margin-top:12px"><button class="btn" id="dg">Entrer</button><button class="btn secondary" id="dx">Fermer</button></div></div>';$('#dx').onclick=()=>modal.hidden=true;$('#dg').onclick=()=>{if($('#dc').value!==CODE)return toast('Accès refusé. Hamoud a changé quelque chose.');modal.innerHTML='<div class="modal-card"><h2>Outils test</h2><button class="btn secondary" id="all">Tout débloquer</button><button class="btn danger" id="reset" style="margin-top:10px">Effacer progression</button></div>';$('#all').onclick=()=>{for(let i=0;i<26;i++)S.done[i]=true;save();toast('Tout débloqué. Dopage de QA.');modal.hidden=true};$('#reset').onclick=()=>{localStorage.removeItem(KEY);location.reload()}}}
function route(i){S.current=i;save();skipArmed=false;[
departure,mri,()=>timing(2,'Kiné : protocole très officiel'),()=>simpleOrder(3,'Bloc opératoire fictif','Puzzle, pas conseil médical.',[0,1,2,3],['🟦 L4','🟪 L5','🟡 Disque','❤️ Courage'],'Dos fictivement réparé. Hamoud conserve l’outil.'),gyno,
()=>simpleOrder(5,'La cave','Raphy range. Mehdi récoltera les mérites.',[0,1,2,3],['📦 Câbles','🎄 Déco','🪛 Objet inconnu','🐈 Hamoud'],'Cave rangée. Mehdi : « on a bien géré ».'),
()=>simpleOrder(6,'Architecte','Le client change d’avis toutes les 43 secondes.',[0,2,1,3],['🏠 Ouvrir','🧱 Refermer','☀️ Lumière','🗄️ Rangement'],'Le client adore. Il veut tout changer demain.'),
()=>canvasGame(7,'Peinture'),()=>simpleOrder(8,'Le lavabo','Une pièce en trop ? Mehdi dit que le fabricant exagère.',[0,1,2,3,5,4],['🛁 Vasque','🚰 Robinet','⭕ Joint','〰️ Siphon','🔴 Chaud','🔵 Froid'],'Montage réussi. Chaud et froid ont choisi la rébellion.'),
()=>simpleOrder(9,'Batterie','Puzzle abstrait, pas tutoriel mécanique.',[0,2,1,3],['A','B','C','D'],'Système restauré. Pile de clé faible. Évidemment.'),
()=>canvasGame(10,'Nettoyage voiture',true),school,()=>quiz(12,'Opération dodo','Sept excuses. Une seule mission : sortir vivante de la chambre.',QGIRL,'👧🏻❄️'),()=>quiz(13,'Mission super-héros','Sept questions auxquelles aucun adulte n’était préparé.',QBOY,'🦸🏻‍♂️'),mojito,coffee,customs,algeria,horror,house,unknown,escapeGame,trial,calm,unsaid,final][i]()}
if(S.unlocked){if(S.storyDone)route(S.current);else opening()}else lock();